### ISSUE TITLE
import javax.swing.event  找不到

### ISSUE THREAD

**Issue by zhugg** [hiliving/DlanPlay#1]
E:\Demo\DlanPlay-master\clinglibrary\src\main\java\org\fourthline\cling\support\contentdirectory\ui\ContentTreeExpandListener.java:22: 错误: 程序包javax.swing.event不存在
import javax.swing.event.TreeExpansionEvent;
                        ^
请问这是问什么啊?

**Comment by hiliving** [comment]
project下面的gradle版本号不能高于3.0.0，你是不是改了------------------ 原始邮件 ------------------
发件人: "zhugg"<notifications@github.com>
发送时间: 2019年10月19日(星期六) 下午3:25
收件人: "hiliving/DlanPlay"<DlanPlay@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [hiliving/DlanPlay] import javax.swing.event  找不到 (#1)



E:\Demo\DlanPlay-master\clinglibrary\src\main\java\org\fourthline\cling\support\contentdirectory\ui\ContentTreeExpandListener.java:22: 错误: 程序包javax.swing.event不存在
 import javax.swing.event.TreeExpansionEvent;
 ^
 请问这是问什么啊?
 
&mdash;

**Comment by zhugg** [comment]
嗯嗯 是的 我编译后就提示我gradle太老 让我升级

**Comment by hiliving** [comment]
改成3.0.0应该可以了吧------------------ 原始邮件 ------------------
发件人: "zhugg"<notifications@github.com>
发送时间: 2019年10月19日(星期六) 下午3:45
收件人: "hiliving/DlanPlay"<DlanPlay@noreply.github.com>;
抄送: "huangyong"<1195996300@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [hiliving/DlanPlay] import javax.swing.event  找不到 (#1)



嗯嗯 是的 我编译后就提示我gradle太老 让我升级
 
&mdash;

**Comment by zhugg** [comment]
不行的  和我的studio不兼容
找到了新方法
在build.gradle中加入依赖
implementation files ('D:/soft/eclipse/jdk/jre/lib/rt.jar')
把这个jar包加上就可以了 
多谢大佬
